### PR TITLE
Change platform.sh logo colors

### PR DESCRIPTION
**Pull request by goetas**
Before:
image

3.9kb

After:
image
2.2kb

I think this change should be reviewed also by @Crell

### CODE REVIEW

**Comment by Crell** [comment]
I just spoke with our marketing people, and they said this was acceptable.  That said, we also have a white version of the logo that can be used if that looks OK, which would be preferable.

**Comment by goetas** [comment]
@Crell if you can provide me a white version, I can try it and then you can decide which one do you prefer.

The reason of this PR is that in my opinion the dark version is very ugly and not readable. I colorized it with the same green of the font color, but if while looks nice and platform.sh prefers it, for me is more than ok!

**Comment by Crell** [comment]
There's SVGs and PNGs here: https://platform.sh/logos/

Link to whichever works better for you.

**Comment by goetas** [comment]
image


The while version fits well. @Crell let me know if you are ok with it.

**Comment by Crell** [comment]
Endorse.  Thanks!

**Pull request merged**
