### PR TITLE
Heading links

### LINKED ISSUE #303: Allow linking to specific parts of the page
Perhaps a continuation of #143 and similar to other standards/rfcs published on the 'net, it would be very useful to be able to link to parts of the the documents, at the very least, to the headers, but maybe even individual paragraphs and bullet points.

For example, https://www.php-fig.org/psr/psr-1/#1-overview-6 would link to the _"Class constants MUST be declared in all upper case with underscore separators."_ bullet point.

Side note: could be nice to have compatibility with github-rendered anchors (eg [PSR-1-basic-coding-standard.md#1-overview](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview)).

### PR DESCRIPTION
**Pull request by vdelau**
Fixes #303

### CODE REVIEW

**Comment by Jean85** [comment]
Closing and reopening to trigger PSH build (it was misconfigured)

**Review by Jean85 — APPROVED** [review]
Great, it works!!

Tested on the environment: https://www---pr-304-hnfhj7a-ovkfaqrdltr5s.us.platform.sh/psr/psr-6/#pool

**Comment by Jean85** [comment]
Original issue had:

> Side note: could be nice to have compatibility with github-rendered anchors (eg [PSR-1-basic-coding-standard.md#1-overview](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview)).

Is this unattainable?

**Comment by vdelau** [comment]
> Is this unattainable?

I think it is, I've removed the prefixes it would use by default, which I think leads to the same ID's. I did just notice that `display: none;` does not play nice with target anchors, I'm changing this to `visibility: hidden`.

**Review by Jean85 — APPROVED** [review]
Great! Let's merge it!

**Pull request merged**
