### PR TITLE
Reflect PSR evolution bylaw change

### PR DESCRIPTION
**Pull request by iansltx**
Just updating the submodule probably isn't enough here, but figured I'd get this started.

Preview available at https://www---pr-270-ks253ky-ovkfaqrdltr5s.us.platform.sh/

### CODE REVIEW

**Comment by iansltx** [comment]
```
    W: - output_dev/bylaws/psr-evolution/index.html
    W:   *  linking to internal hash # that does not exist (line 140)
    W:      <a href="#">psr/container version 1.1</a>
    htmlproofer 3.10.2 | Error:  HTML-Proofer found 1 failure!
```

@Jean85 How do we want to handle this? Need to either get HTML-Proofer to let this slide or revise the anchor in the bylaw to point somewhere useful...the latter of which doesn't make a lot of sense since this is an example of a change that we haven't made yet.

**Comment by Jean85** [comment]
Does it complain if we use https://packagist.org/packages/psr/container#1.1.0 ? If yes, I would use the link anyway without the anchor.

**Comment by iansltx** [comment]
Not sure. Would need to create a branch of the standards repo and submodule that in. May be able to try that tonight.

**Comment by Jean85** [comment]
I've checked locally, that link (https://packagist.org/packages/psr/container#1.1.0) works, it makes the check pass. I've pushed the fix on the bylaw, I'll re-update the submodule again.

**Comment by Jean85** [comment]
Site is deployed correctly. The article is fine, apart from the blockquote:

image

We're probably missing some CSS..

**Comment by Jean85** [comment]
Ok, CSS updated:

immagine

**Pull request merged**
