### PR TITLE
Change Docker configuration to use Debian Buster instead of Alpine to have proper iconv support

### PR DESCRIPTION
**Pull request by vdelau**
I had two problems while running the Docker based dev environment:
- Alpine's `iconv` support is not complete and does not support `//TRANSLIT`
- Composer on Docker on WSL creates bad proxy files in `vendor/bin`, I've bypassed those

### CODE REVIEW

**Comment by Jean85** [comment]
Iconv issues with Alpine are known from https://github.com/docker-library/php/issues/240 and can be fixed with this snipped added before ext installations:
```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Comment by vdelau** [comment]
Composer on WSL issue reported at Sculpin: https://github.com/sculpin/sculpin/pull/463

**Comment by Jean85** [comment]
Fix on Scuplin released as 3.1.1: https://github.com/sculpin/sculpin/commit/88aef549743e53260fe9c71d1c9d37589718c657

Can we convert this PR to a requirement to that version and the application of the Alpine workaround?

**Comment by vdelau** [comment]
I think this PR can be closed, as you already pinned a specific PR version (with iconv patch: `dev-master#2aed37a as 3.1.2`) that includes this fix.

**Pull request closed without merging**
